#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE SCHEMA raw;

	CREATE USER $METABASE_POSTGRES_USER WITH PASSWORD '$METABASE_POSTGRES_PASSWORD';
	CREATE DATABASE $METABASE_POSTGRES_DB with owner $METABASE_POSTGRES_USER;
	GRANT ALL PRIVILEGES ON DATABASE $METABASE_POSTGRES_DB TO $METABASE_POSTGRES_USER;

	CREATE USER $DAGSTER_POSTGRES_USER WITH PASSWORD '$DAGSTER_POSTGRES_PASSWORD';
	CREATE DATABASE $DAGSTER_POSTGRES_DB with owner $DAGSTER_POSTGRES_USER;
	GRANT ALL PRIVILEGES ON DATABASE $DAGSTER_POSTGRES_DB TO $DAGSTER_POSTGRES_USER;
EOSQL